### ISSUE TITLE
Inconsistency gauge icons

### ISSUE THREAD

**Issue by cascornelissen** [Templarian/WindowsIcons#206]
This might be on purpose but it looks off...
I'd be happy to fix them and create a pull request if you don't have the time.

![2015-01-23_13-34-13](https://cloud.githubusercontent.com/assets/1304939/5874658/a939a774-a304-11e4-83a6-69cdc0a03012.png)

**Comment by Templarian** [comment]
Not sure how I missed this notification, been really distracted building out the new icon platform. Each icon is getting a complete redesign from scratch, so I fast tracked this and added them.

Preview:
![appbar gauge 0](https://cloud.githubusercontent.com/assets/338885/6161311/affe5138-b234-11e4-8b63-b296394a1618.png) ![appbar gauge 25](https://cloud.githubusercontent.com/assets/338885/6161313/b349c494-b234-11e4-8292-e57a482c3957.png) ![appbar gauge 50](https://cloud.githubusercontent.com/assets/338885/6161315/b5178b44-b234-11e4-9026-28916b4bbe70.png) ![appbar gauge 75](https://cloud.githubusercontent.com/assets/338885/6161316/b76bf0ec-b234-11e4-9999-3781464ae49b.png) ![appbar gauge 100](https://cloud.githubusercontent.com/assets/338885/6161318/baa4e750-b234-11e4-80ff-740bfb4a2fc8.png)

**Comment by cascornelissen** [comment]
Looks great, I can't wait for the the new platform!
