### ISSUE TITLE
Created a bunch of icons

### ISSUE THREAD

**Issue by stefan-schweiger** [Templarian/WindowsIcons#207]
I've created a bunch of icons based on your icon pack, if you want them let me know which of those you like and whats the best way of sending the design files to you.

appbar.calendar.tear
![appbar calendar tear](https://cloud.githubusercontent.com/assets/3532342/5919870/19917584-a638-11e4-8181-5db02d4a69e5.png)
appbar.calendar.event
![appbar calendar event](https://cloud.githubusercontent.com/assets/3532342/5919955/eec8accc-a638-11e4-9c3d-df5f7512a4fd.png)
appbar.home.empty.filled
![appbar home empty filled](https://cloud.githubusercontent.com/assets/3532342/5919873/19961788-a638-11e4-9e7c-10ac5aec30f1.png)
appbar.home.filled
![appbar home filled](https://cloud.githubusercontent.com/assets/3532342/5919875/19977ee8-a638-11e4-86c5-a1a54d819f87.png)
appbar.home.variant.filled
![appbar home variant filled](https://cloud.githubusercontent.com/assets/3532342/5919872/19949cbe-a638-11e4-9882-beb7704241d1.png)
appbar.people.business
![appbar people business](https://cloud.githubusercontent.com/assets/3532342/5919871/19923af0-a638-11e4-8774-08c2b4e2af0b.png)
appbar.speechbubble
![appbar speechbubble](https://cloud.githubusercontent.com/assets/3532342/5919877/19a8a68c-a638-11e4-923d-67a37dd5a9db.png)
appbar.speechbubble.add
![appbar speechbubble add](https://cloud.githubusercontent.com/assets/3532342/5919874/1996235e-a638-11e4-827e-4c5a72bb9e98.png)
appbar.timesheet
![appbar timesheet](https://cloud.githubusercontent.com/assets/3532342/5919878/19b0800a-a638-11e4-8aa0-6bd0af1846ed.png)
appbar.timesheet.tear
![appbar timesheet tear](https://cloud.githubusercontent.com/assets/3532342/5919876/19a86a50-a638-11e4-8513-265330e5c398.png)
appbar.company
![appbar company](https://cloud.githubusercontent.com/assets/3532342/5919934/b5cd36fe-a638-11e4-90ee-b53873263fe1.png)

**Comment by Templarian** [comment]
Can you export these to SVG? If so please share your email (I'll delete it out of the comment once I have you added).

I'll just give you a contributor account to the new system that is in alpha.

**Comment by stefan-schweiger** [comment]
yes I can do that no problem.

my email adress is: staeff[at]me.com

**Comment by Templarian** [comment]
Warning: Please select the Modern UI Icons package before clicking the add icon button at the top (it will throw an error about wrong sized icon if you do not).

This system is still being converted to handle multiple 76x76 (it was built for 24x24). So ignore any cosmetic issues for now.

Reply here if you have any questions, but I'm going to close this issue for now.

**Comment by stefan-schweiger** [comment]
Thank you!

A bug I've discovered is that I can't add icons with a dot in the name (but I can change the name afterwards to contain a dot). Also should I name the icons "appbar.company" or only "company"?

**Comment by Templarian** [comment]
Yea, I edited my comment above trying to clarify the naming. They need to be hyphenated. The names will be transformed during the export step.

I can't make it handle multiple path imports. Please use layers in the source files. The font generation that will be ran needs to have pristine path data to work. Any small defect and it explodes.

**Comment by stefan-schweiger** [comment]
The icons are now added ;)

**Comment by Templarian** [comment]
Now I tell you the annoying news, I'm only 20/1200 icons into importing Modern UI Icons. If I get a few minutes I'll manually place your icons into the legacy site.

I plan to have the new site online in 3 months before Microsoft Build 2015. It will look similar to MaterialDesignIcons.com at launch.
