### ISSUE TITLE
License notes are misleading

### ISSUE THREAD

**Issue by Wuzzy2** [Templarian/WindowsIcons#226]
From the license notes:

```
## Understand Your Rights
No Attribution and No Derived Works
http://creativecommons.org/licenses/by-nd/3.0/ *

- If your project is open source include this license file in the source.
```

The last sentence is misleading. As soon you include any of the icons in an open source software, **it immediately ceases to be open source**. 
This is because of the ND clause, which is in violation of point 3 in the Open Source Definition (https://opensource.org/definition).
Derivated works must be permitted in open source software *by definition*.
In other words, the ND clause is **incompatible** with open source software.

I don't know why you chose the ND clause, but here's what I suggest:

* If the ND clause was added by accident, please remove it, turning the license to CC BY. The free software community and open source community will thank you for this
* If you insist on the ND clause (for whatever reason), please remove the misleading sentence. Maybe state clearly that inclusion into open source software means it will no longer be open source software

FYI: These Creative Commons licenses are compatible with open source:

* CC0
* CC BY
* CC BY-SA

These licenses are incompatible:

* CC BY-ND
* CC BY-NC-ND
* CC BY-NC
* CC BY-NC-SA

**Comment by Templarian** [comment]
This project is unmaintained, thanks for looking into this, but no updates are being made at this time.

Learn more: #220
