### ISSUE TITLE
modernuiicons.com not avaliable

### ISSUE THREAD

**Issue by tsukinoko-kun** [Templarian/WindowsIcons#227]
modernuiicons.com was a good page to see all the icons, it is not available anymore

**Comment by Templarian** [comment]
Yeah, the domain will be expiring soon also. I shut down the host 2 weeks ago.

I think I have them imported into the new database, so could do something, but not sure it's worth it.

There are so many better icon packs out there. Definitely transition to MaterialDesignIcons.com if you can.
