### ISSUE TITLE
appbar.thermometer

### ISSUE THREAD

**Issue by JeroenVandezande** [Templarian/WindowsIcons#96]
would look like a old style Mercury-in-glass thermometer.
for use when showing temperatures.

**Comment by ScottRHorton** [comment]
Thanks for adding! Sidenote: there is a typo on the Kelvin thermometer, the units on Kelvin are not degrees. https://en.wikipedia.org/wiki/Kelvin

**Comment by Templarian** [comment]
@ScottRHorton This icon pack is deprecated and does not receive updates. Thanks though!

**Comment by ScottRHorton** [comment]
Wow thanks for the response :-)! is there a new icon pack I should be using
instead? The makers of the icons did great work, they all look very
professional.

**Comment by Templarian** [comment]
I run https://materialdesignicons.com/ now (very large and active community, just did a release today for it). For Windows I'm still working on the release for Modern Icons that will be similar to this deprecated project, but for Modern Design Language 2.0 icons.

Modern Icons will follow Material Design Icons' same community-led style.
